version: '3.9'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
